version: "3.8"

services:
  monolith:
    container_name: monolith
    hostname: monolith
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - '8081:8080'
      - '8085:8085'
    env_file:
      - docker/.env
    depends_on:
      - postgres
    command: [ "./wait-for", "postgres:5432", "--", "/shops/monolith" ]
  postgres:
    container_name: postgres
    hostname: postgres
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: itsasecret
    ports:
      - '5434:5432'
    volumes:
      - 'pgdata:/var/lib/postgresql/data'
      - './docker/database:/docker-entrypoint-initdb.d'

volumes:
  pgdata:
